### ISSUE TITLE
Conectar a API Externa.

### ISSUE THREAD

**Issue by fredarend** [CursosCod3r/mean-primeira-app#3]
Boa tarde, Leonardo!
Quando tento consumir qualquer API externa, obtenho o seguinte erro no navegador: 

Chrome: 
`Failed to load http://fipeapi.appspot.com/api/1/motos/marcas.json: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 405.`

Mozilla:
`Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em http://fipeapi.appspot.com/api/1/carros/marcas.json. (Motivo: o cabeçalho CORS 'Access-Control-Allow-Origin' não está presente).`

Função: 
```

  vm.getMarcasFipe = function() {
    vm.tipo = vm.alerta.veiculos.tipo
    const urlMarca = `http://fipeapi.appspot.com/api/1/${vm.tipo}/marcas.json`
    $http.get(urlMarca).then(function(resp) {
      vm.marcasFipe = resp.data
    })
  }


```
vm.tipo refere-se a 'carro' ou 'moto'.
Neste exemplo estou tentando buscar marcas de carros ou motos da tabela fipe. Caso executar esse get no postman verá que está funcionando, assim como funcionava antes de implementar a parte de autenticação. 

Agradeço a atenção!

**Comment by flavioccf** [comment]
@fredarend você está fazendo a chamada via JavaScript, como está ocorrendo a mensagem CORS [https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Controle_Acesso_CORS](url) é recomendável que você utilize algum backend (PHP, etc) para fazer essa requisição por cURL ou alguma outra forma que não entre no Controle de Acesso.
